import { Inter } from 'next/font/google'
import './globals.css'

import Zoho from '~/app/components/Zoho'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Zoho>
          {children}
        </Zoho>
      </body>
    </html>
  )
}
